name: Publish Node Docker
on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "" --password-stdin
        docker egco341 build -t nipatsa/nodedockergit:latest .
        docker push nipatsa/nodedockergit:latest
